### ISSUE TITLE
when I compress the SRR1294116 single-end data, commend reported fault.

### ISSUE THREAD

**Issue by huangnengCSU** [yuansliu/minicom#1]
<img width="727" alt="wx20190202-124310 2x" src="https://user-images.githubusercontent.com/28866823/52167387-4269aa00-26e8-11e9-9162-5c004b2d9a6c.png">

OS: ubuntu 16.04
memory: 1T
cpu cores: 40
gcc version: 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)

**Comment by yuansliu** [comment]
Hi @huangnengCSU,

Thank you very much for your reporting this bug. But, I cannot reproduce this bug on my computer as the following picture. Note that I terminate the program after contigs generation. More information should be provided please. 

![image](https://user-images.githubusercontent.com/7776655/52170427-11e44780-279e-11e9-88c0-0d1cdde2bb9c.png)

**Comment by huangnengCSU** [comment]
I download the SRR1294116.sra data and use fastq-dump command to generate the fastq format data (size about 15Gb). Then I clone your repositories to my local server, and follow the install command. after that do nothing, just run the tool. I try it on two different servers and both report this bug. Did you try it on a new computer, and it also run successfully?

**Comment by yuansliu** [comment]
Hi @huangnengCSU,

The program has been tested on ubuntu and redhat system (version g++ >= 5.3.1). Please show the stack size of your system via ```ulimit -s```.

**Comment by huangnengCSU** [comment]
ulimit -s is  8192

Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.10' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)

**Comment by yuansliu** [comment]
Please change the stack size ```ulimit -s unlimited``` and test again.

**Comment by huangnengCSU** [comment]
<img width="764" alt="wx20190202-200439 2x" src="https://user-images.githubusercontent.com/28866823/52171158-e1f95d80-2725-11e9-9f4a-fdb072d581a5.png">

is there other settings?

**Comment by yuansliu** [comment]
I cannot use ubuntu system now. 

Could you please first test the small file ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR554/SRR554369/SRR554369_1.fastq.gz.

**Comment by huangnengCSU** [comment]
ok, i will have a try, thank you.

**Comment by huangnengCSU** [comment]
when testing the small data SRR554369_1.fastq(367 Mb), it works. So the size of the input file influences the program running.

**Comment by yuansliu** [comment]
The result is almost the same as I expected. It seems that your system cannot new enough memory for large dataset.

Could you please list the results of ```ulimit -a```.

**Comment by huangnengCSU** [comment]
<img width="404" alt="wx20190203-191535 2x" src="https://user-images.githubusercontent.com/28866823/52184987-29e0b900-27e8-11e9-8d19-98ff8799b1f7.png">

**Comment by yuansliu** [comment]
Hi @huangnengCSU,

Please update the src file "kthread_cb.c". The bug is caused by "alloca". Although stack size is set to unlimited, it cannot work well in Ubuntu while it works well in redHat.
